### PR TITLE
Adding tile with two city features fix

### LINKED ISSUE #76: City manager fails to properly merge a single city with a single tile that has 2 different city features
### Graphical example
image

### Regression test
https://github.com/YetAnotherSpieskowcy/Carcassonne-Engine/commit/d0ce6e39ec5d5ad6d7e489875cbb1465e6b092a8

### Test output
```
$ go test -count=1 ./pkg/game -run TestRegressionGHIssue76  
--- FAIL: TestRegressionGHIssue76 (0.00s)
panic: city manager did not find city: elements.PlacedFeature{Feature:feature.Feature{FeatureType:2, ModifierType:0, Sides:0x30}, Meeple:elements.Meeple{Type:0x0, PlayerID:0x0}} at position position.Position{x:1, y:1} [recovered]
	panic: city manager did not find city: elements.PlacedFeature{Feature:feature.Feature{FeatureType:2, ModifierType:0, Sides:0x30}, Meeple:elements.Meeple{Type:0x0, PlayerID:0x0}} at position position.Position{x:1, y:1}

goroutine 18 [running]:
testing.tRunner.func1.2({0x555d60, 0xc0001843a0})
	/usr/lib/go-1.22/src/testing/testing.go:1631 +0x24a
testing.tRunner.func1()
	/usr/lib/go-1.22/src/testing/testing.go:1634 +0x377
panic({0x555d60?, 0xc0001843a0?})
	/usr/lib/go-1.22/src/runtime/panic.go:770 +0x132
github.com/YetAnotherSpieskowcy/Carcassonne-Engine/pkg/game/field.(*Field).Expand(0xc000190df8, {0x5c21c8, 0xc0001cc080}, {{0xc000196cf0?, 0x47?, 0x4a?}})
	/home/ubuntu/work/Carcassonne-Engine/pkg/game/field/field.go:109 +0x7c5
github.com/YetAnotherSpieskowcy/Carcassonne-Engine/pkg/game.TestRegressionGHIssue76(0xc0001be4e0)
	/home/ubuntu/work/Carcassonne-Engine/pkg/game/field_test.go:236 +0xccf
testing.tRunner(0xc0001be4e0, 0x5921e8)
	/usr/lib/go-1.22/src/testing/testing.go:1689 +0xfb
created by testing.(*T).Run in goroutine 1
	/usr/lib/go-1.22/src/testing/testing.go:1742 +0x390
FAIL	github.com/YetAnotherSpieskowcy/Carcassonne-Engine/pkg/game	0.003s
FAIL
```

### PR DESCRIPTION
**Pull request by BognaLew**
Fixes #76

### CODE REVIEW

File: pkg/game/city/city_manager.go [hunk 1]
```diff
@@ -121,13 +115,12 @@ func (manager *Manager) CanBePlaced(tile elements.PlacedTile, feat elements.Plac
 		// no City features or only has a completely new city
 		return true
 	}
-	citiesToJoin := manager.findCitiesToJoin(foundCities, tile)
+	citiesToJoin := manager.findCitiesToJoin(foundCities, feat.Sides)
 	// this may return an empty list for features that have no cities to join with
```
Comment (Jackenmen) [inline pkg/game/city/city_manager.go:119]: nit: probably should move this comment
```suggestion
	// this may return an empty list for features that have no cities to join with
	citiesToJoin := manager.findCitiesToJoin(foundCities, feat.Sides)
```

**Review by Jackenmen — APPROVED** [review]
I left one nitpicky review comment but overall looks good to me.

**Review by bstrzelecki — APPROVED** [review]
