### PR TITLE
Fix expansion to another field feature when validating placement

### LINKED ISSUE #86: Field instance cannot expand to another feature on the checked tile, if it's not on the board
### Description
This TODO needs to be addressed:
https://github.com/YetAnotherSpieskowcy/Carcassonne-Engine/blob/a711a81f37b51efd849b63710c001a60ab8971fb/pkg/game/board.go#L240-L243

### Graphical example 
image

### Regression test
Already present in the affected branch (#62), you'll just need to remove the `t.Skip` to have it run:
https://github.com/YetAnotherSpieskowcy/Carcassonne-Engine/blob/a711a81f37b51efd849b63710c001a60ab8971fb/pkg/game/board_test.go#L137-L177

### Test output
```
$ go test -count=1 ./pkg/game -run TestBoardFieldCanBePlacedReturnsFalseWhenExpandToFieldWithMeepleHappensOverAnotherField
--- FAIL: TestBoardFieldCanBePlacedReturnsFalseWhenExpandToFieldWithMeepleHappensOverAnotherField (0.00s)
    board_test.go:173: expected false, got true instead
FAIL
FAIL	github.com/YetAnotherSpieskowcy/Carcassonne-Engine/pkg/game	0.002s
FAIL
```

### PR DESCRIPTION
**Pull request by Lenetis**
Fixes #86

### CODE REVIEW

File: pkg/game/board.go [hunk 1]
```diff
@@ -252,14 +252,9 @@ func (board *board) fieldCanBePlaced(tile elements.PlacedTile, feat elements.Pla
 
 	// TODO: Field instance cannot expand to another feature on the tile checked by
```
Comment (bstrzelecki) [inline pkg/game/board.go:253]: Is this comment still necessary?

File: pkg/game/field/field.go [hunk 2]
```diff
@@ -119,16 +132,51 @@ func (field *Field) Expand(board elements.Board, cityManager city.Manager) {
 	field.features = newFeatures
 }
 
+// Returns true if the field has lesser or equal number of meeples than maxMeepleCount, and false otherwise
```
Comment (Jackenmen) [inline pkg/game/field/field.go:135]: While this description of the function is technically true, it does not necessarily make it clear how this is useful, i.e. it can be used to check whether a meeple could be placed on the given field.
With that use case in mind, the way to achieve this should probably also be documented since it's not necessarily clear what `maxMeepleCount` should be set to - this actually depends on whether the tile has any meeple on a field feature (always the case for the only usage - i.e. `fieldCanBePlaced` - which is why it needs to be passed with `1`).

File: pkg/game/field/field.go [hunk 3]
```diff
@@ -119,16 +132,51 @@ func (field *Field) Expand(board elements.Board, cityManager city.Manager) {
...
+func (field Field) IsFieldValid(board elements.Board, maxMeepleCount int) bool {
```
Comment (Jackenmen) [inline pkg/game/field/field.go:136]: a) it should be documented that this method cannot be used twice since it alters the `field`'s state (maps are pointers so they point to the same map on copy)
b) it would be easier to realise that this can modify the field if it were using a pointer receiver

**Review by Jackenmen — CHANGES_REQUESTED** [review]

File: pkg/game/field/field.go (hunk 3 above)
Comment (Lenetis) [reply pkg/game/field/field.go:140]: changed so that it doesn't modify the original field.features, and instead works on a copy

**Review by bstrzelecki — APPROVED** [review]
