### PR TITLE
Fixed log performance

### LINKED ISSUE #123: Avoid serialization for null logger

### PR DESCRIPTION
**Pull request by bstrzelecki**
Fixes #123 
``` 
                       │   0.bench    │                1.bench                │
                       │    sec/op    │    sec/op     vs base                 │
LongCity-32                2.036 ± ∞ ¹    1.893 ± ∞ ¹        ~ (p=1.000 n=1) ²
ManySmallCities-32        80.57µ ± ∞ ¹   48.12µ ± ∞ ¹        ~ (p=1.000 n=1) ²
LongField-32               2.052 ± ∞ ¹    2.313 ± ∞ ¹        ~ (p=1.000 n=1) ²
ManySmallFields-32        68.22µ ± ∞ ¹   37.37µ ± ∞ ¹        ~ (p=1.000 n=1) ²
LongMonastery-32           2.199 ± ∞ ¹    2.002 ± ∞ ¹        ~ (p=1.000 n=1) ²
ManySmallMonasteries-32   56.18µ ± ∞ ¹   35.97µ ± ∞ ¹        ~ (p=1.000 n=1) ²
SingleExtraLongRoad-32     2.060 ± ∞ ¹    2.073 ± ∞ ¹        ~ (p=1.000 n=1) ²
ManyShortRoads-32         59.45µ ± ∞ ¹   36.32µ ± ∞ ¹        ~ (p=1.000 n=1) ²
geomean                   11.69m         8.991m        -23.06%
```

### CODE REVIEW

File: pkg/logger/logger.go [hunk 1]
```diff
@@ -54,3 +54,20 @@ func (logger *BaseLogger) CopyTo(dst Logger) error {
...
+}
+
+func (*EmptyLogger) AsWriter() io.Writer {
+	return nil
+}
+
+func (*EmptyLogger) LogEvent(eventName EventType, event interface{}) error { //nolint:revive // causes gopy to fail
+	return nil
+}
+func (*EmptyLogger) CopyTo(dst Logger) error { //nolint:revive // causes gopy to fail
```
Comment (Jackenmen) [inline pkg/logger/logger.go:71]: Nit: inconsistent formatting
```suggestion

func (*EmptyLogger) CopyTo(dst Logger) error { //nolint:revive // causes gopy to fail
```

**Review by Jackenmen — APPROVED** [review]
I don't think the existing usage of `AsWriter()` (i.e. `FileLogger.CopyTo()` method) accepts `nil` as the return value but that also shouldn't matter because the existing usage of `CopyTo()` only passes `FileLogger`s when using that function. I guess it would be good to document this but it's not important enough for me to block this.

**Review by BognaLew — APPROVED** [review]
